import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/react-toastify/ToastProvider";
import { StateContextProvider } from "@/contexts/common/StateContext";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansJP.variable} antialiased`}
      >
        <ToastProvider>
          <StateContextProvider>
            {children}
          </StateContextProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
